rc-01 to main (#38)
* init: v0.2

* test: add protocol test & license

* :ambulance: fixed bad ip format injection in rule engine.

* Feat/iprange (#2)

* :sparkles: added ipv4 & ipv6 ranges, adapted connect new IpAddr type. (was Ipv4Addr before)

* :fire: removed useless comment.

* Smtp Timeout (#4)

* feat: better handling timeout on io service

* fix: write 451 on timeout & update message

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* Struct/rule rcpt (#5)

* :art: . rcpt rules are now executed for each RCPT TO command received.
      . rules are cleared after each evaluation, this enables us to
        inject back variables that could have changed in rhai's context
        (helo, mail, rcpt ...) into fresh rule objects.

* :arrow_up: file fqdn & addr are parsed using the addr crate.

* Test/ci (#7)

* test: add test protocol tls & ci github

* hotfix: name ci script

* feat: add version in config (unused)

* feat: merge log4rs and vsmtp.toml config files (#6)

* feat: merge log4rs and vsmtp.toml config files

* fix: add clap and -h

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* Update README.md

* feat: add domain in config (#8)

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* Rename Personnal.vsl to example.vsl

* Delete doc vSL.md

* Feat/rules global variables (#9)

* :sparkles: added date & time variables into rhai's scope.

* :sparkles: added msg_id to the injected variables in rhai's context.

* :sparkles: added the msg_id configuration variable.
	   the rule engine outputs better error messages when failing.
	   the DUMP action can only be called from the mail stage.

* ROADMAP reviewed

* ROADMAP review

* Spelling

* Update FEATURES.md

* Update ROADMAP.md

* Update ROADMAP.md

* Update ROADMAP.md

* Add only incoming mails in RC1

* Update ROADMAP.md

* Add wiki

* fix: to process filename (#11)

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* :sparkles: implementation of the BLOCK action. (#10)

* :sparkles: implementation of the BLOCK action.
	   block replaces the QUARANTINE action.
	   block force skip all rules and write the email
	   at the specified directory using a message id.

* :truck: moved rule file to test files.

* feat: add error counter and soft/hard error params, causing sleep/close with message (#12)

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* Test/rule engine (#13)

* :white_check_mark: added a simple rhai script creating objects.

* :white_check_mark: implemented test setup for the rule engine.
	           added a simple object parsing test.

* :white_check_mark: added functionnals test regarding object parsing for the rule engine.

* :truck: changed envelop fields: mail_from -> mail, recipients -> rcpt.

* :art: moved Var datastructure to a obj.rs file and renamed it to Object.
      added documentation for the Object datastructure.

* :truck: moved the operation queue to its own file, implemented iterator for a better api.

* :truck: moved vsl module into its own action.rs file.

* :pencil: added documentation for the rule engine.

* :truck: moved rule engine test files in their own test directory.

* :white_check_mark: added tests for the operation queue.

* :white_check_mark: added tests for connect matching.

* :white_check_mark: added a macro to easly generate rule matching tests.

* :white_check_mark: added all tests for the helo stage matching.

* :white_check_mark: finished matching stage function tests.

* :white_check_mark: added a simple fuzz entrpoint for the rule engine.

* :wrench: added vscode debugging configuration. (#VIR-106)

* :sparkles: added the USER_EXISTS rule matching function. (#15)

* :sparkles: added the USER_EXISTS rule matching function.
	   an object of type var, file or grp will be used
	   to check if the/all user(s) exists on the system.

* :rotating_light: fixed lint error on src/rules/actions.rs:350:32.

* Fix receiver (#14)

* fix: vec<u8> => String, add connection data in mail context

* :arrow_up: externalised msg_id in the mail receiver instead of the envelop.

* fix: use connection timestamp & mail from timestamp

* fix: some clear of buffer between steps and mock test

* :ambulance: applied pr comments suggestions.

* :sparkles: added a first unclean version of the msg_id system.

* fix: warn lint

Co-authored-by: Mathieu Lala <m.lala@viridit.com>
Co-authored-by: ltabis <tab.rysak70@gmail.com>

* Refact/config (#16)

* fix: vec<u8> => String, add connection data in mail context

* :arrow_up: externalised msg_id in the mail receiver instead of the envelop.

* fix: use connection timestamp & mail from timestamp

* fix: some clear of buffer between steps and mock test

* fix: config and update test

* fix: fuzz test receiver

Co-authored-by: Mathieu Lala <m.lala@viridit.com>
Co-authored-by: ltabis <tab.rysak70@gmail.com>

* Feat/add args (#18)

* feat: add argv WIP

* feat: imporve logger target and add option args in config

* doc: update config doc

* hotfix config pag

* feat: local dev config

Co-authored-by: Mathieu Lala <m.lala@viridit.com>
Co-authored-by: paguardiolle <pa.guardiolle@viridit.com>

* Struct/local user crate#vir 92 (#19)

* :art: replaced user fetching command by a libc wrapper crate.
      added a cache for users.

* :wrench: changed name of crate: v-smtp -> vsmtp.

* :white_check_mark: updated RhaiEngine's test system:
		    - removed old mocking system
		    - possibility to construct the rhai engine with mocked users.

* :white_check_mark: added a mockup system to test users.

* :rotating_light: fixed lint error.

* :rotating_light: fixed lint error.

* initial commit

* Fix/cpu usage (#20)

* fix: tcp stream use tokio

* test: add fuzzer for config parser

* hotfix: lint

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* Feat/rules src dir#vir 114 (#21)

* :sparkles: added default rules dir.

* :ambulance: removed unwraps and replaced by expect or better error handling.

* :arrow_up: better error message for certificates.

* :arrow_up: cleaned up vsmtp.toml.

* :wrench: added rules table to dev config.

* feat: add custom smtp code (#22)

* feat: add custom smtp code

* hotfix

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* Feat/user domain variables#vir 95 (#23)

* :sparkles: added a addr::Address wrapper to send address data into rhai's context.

* :sparkles: replaced all rcpt and mail_from values using the Address struct.

* :ambulance: rule engine is exectued before mail queueing when receiving the data end command.

* :white_check_mark: fixed test with the new Address API.

* :arrow_up: updated dev config.

* :pencil: added notes on MailDir tmp files.

* :sparkles: current resolver delivers mail to the new directory, following maildir spec.
	   recipients unknown to the system will be skiped.

* :ambulance: the resolver wasn't following maildir's folder convetion.

* :arrow_up: (#VIR-126) the maildir email file name is created following this method:
           {timestamp}.Size={content size}.D={deliveries}.ID={rcpt unique_id}.vsmtp

* :white_check_mark: fixed test with new on_data_end api.

* fix: test domain and parsing config (#26)

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* Config : option max rcpt (#25)

* :sparkles: added the rcpt_count_max configuration variable that enables the
	   user to close the connection if there are to much recipients.

* :art: checking rcpt nb after the execution of the rule engine.

* :wrench: updated dev config.

* :pencil: updated config doc.

* :ambulance: removed unused log.

* doc: update readme

* doc: add badge

* Feat/user domain variables#vir 95 (#27)

* :sparkles: added a addr::Address wrapper to send address data into rhai's context.

* :sparkles: replaced all rcpt and mail_from values using the Address struct.

* :ambulance: rule engine is exectued before mail queueing when receiving the data end command.

* :white_check_mark: fixed test with the new Address API.

* :arrow_up: changed Address struct API.
	   user -> local_part

* :sparkles: added rcpts.users & rcpts.domains methods.

* :ambulance: changed users method to local_parts.

* doc: add license & minor fix

* Bench (#29)

* feat: add bench criterion & update ci & test integration

* ci: add benchmark artifact

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* Change on security.md and readme spelling

* url for release

* spelling

* Test/dos (#30)

* test: add Denial of Service testing

* hotfix: remove generated files

* fix: tls enable 'main' cert/key

* fix: sni missing

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* :sparkles: using a mutex to count deliveries, using libc to change ownerships.

* :pencil: renamed actions following the documentation.

* :white_check_mark: fixed compilation errors for tests.

* :white_check_mark: fixed benches tests.

* :white_check_mark: we can re-initialize the engine while testing. (#31)

* Doc/misc (#35)

* Initial commit

* Adding commercial part

* Versioning from RC-X to 0.x.y

* Remove undesired URL

* Create .gitkeep

* Add files via upload

* Test img

* Typo and image

* Dark and light theme logo

* Dark logo

* Add files via upload

* Typo + markdown issues

* Typo + MD errors

* Add files via upload

* Update README.md

* Delete vsmtp white nobckgrd.png

* Delete vsmtp black nobckgrd.png

* Add files via upload

* Update README.md

* :ambulance: fixed merge issues.

* Add tests & Fix state after transfert (#36)

* test: add test for rset

* test: add multiple transfert test & refact on_data_end

Co-authored-by: Mathieu Lala <m.lala@viridit.com>

* Fix/rule engine#vir 145 (#37)

* :wrench: set correct version number.

* :ambulance: added end of line for file logs (https://viridit.atlassian.net/browse/VIR-139)

* :ambulance: the user can send objects in the LOG action. (https://viridit.atlassian.net/browse/VIR-135)

* :ambulance: added function to convert custom types into strings for string interpolation.
	    https://viridit.atlassian.net/browse/VIR-134.
            https://viridit.atlassian.net/browse/VIR-138.

* :ambulance: added better error messages when the engine cannot initalize. (https://viridit.atlassian.net/browse/VIR-136)

* :arrow_up: rule engines only picks up vsl files.

* fixed readme logo

Co-authored-by: Mathieu Lala <m.lala@viridit.com>
Co-authored-by: Mathieu Lala <mathieu.lala@epitech.eu>
Co-authored-by: Pierre-Antoine Guardiolle <94467613+paguardiolle@users.noreply.github.com>
Co-authored-by: paguardiolle <pa.guardiolle@viridit.com>